ALTER TABLE schedule
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE university
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE audiences
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE faculties
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE departments
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE lectures
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE groups
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE students
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE lessons
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE subjects
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;

ALTER TABLE teachers
    ADD COLUMN id BIGSERIAL NOT NULL PRIMARY KEY;